//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu
    {
        public string Sno { get; set; }
        public string Sname { get; set; }
        public string Sgender { get; set; }
        public string Sdormitory { get; set; }
        public string Smajor { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public string Stel { get; set; }
        public Nullable<System.DateTime> Sbrithday { get; set; }
    }
}
